#!/usr/bin/env python

import logging
import argparse

from app import LabelPi

parser = argparse.ArgumentParser()
parser.add_argument('--debug', action='store_true', help='')
args = parser.parse_args()

if args.debug: logging.basicConfig(level=logging.DEBUG)

LabelPi().run()

