#!/usr/bin/env python

import logging
import argparse

from app import LabelWeb

parser = argparse.ArgumentParser()
parser.add_argument('--server', help='Server to use.')
parser.add_argument('--debug', action='store_true', help='Enable debugging mode')
args = parser.parse_args()

if args.debug: logging.basicConfig(level=logging.DEBUG)
server = args.server or ('wsgiref' if args.debug else 'cherrypy')

LabelWeb().run(debug=args.debug, server=server)

